var cv = {
	"address" : "University  of  California, San  Diego<br />Philosophy,  0119<br />9500  Gilman  Drive</br>La  Jolla,  CA  92093-0119",
	"phone" : "Phone:  858  534  6810  (office)<br />Phone:  858  454  6910  (home)",
	"fax" : "Fax: 858 454 8566",
	"email" : "rarneson@ucsd.edu",
	"webpage" : "http://philosophy.ucsd.edu/faculty/rarneson/",
	"personal" : "Born:    June  24,  1945.<br />Marital  status:  Married,  one  stepdaughter.",
	"education" : ["A.B.  magna  cum  laude  with  history  concentration,  Brown  University,  1967.Phi  Beta  Kappa.Pell  Award  in  History.", "1Last  revised:  May,  2018RICHARD  J.  ARNESONCURRICULUM  VITAEUniversity  of  California,  San  DiegoHome  address:Philosophy,  01197369  Draper  Avenue9500  Gilman  DriveLa  Jolla,  CA  92037-5024La  Jolla,  CA  92093-0119Phone:  858  534  6810  (office)Phone:  858  454  6910  (home)FAX:  858  534  8566Email:  RARNESON@UCSD.EDUWeb  page: http://philosophy.ucsd.edu/faculty/rarneson/PERSONALBorn:    June  24,  1945.  Marital  status:  Married,  one  stepdaughter.EDUCATIONA.B.  magna  cum  laude  with  history  concentration,  Brown  University,  1967.Phi  Beta  Kappa.Pell  Award  in  History.Ph.D.  in  philosophy,  University  of  California  at  Berkeley,  1975.    Dissertation:  'John  Rawls's  Theory  of  Justice'    (Advisors:  HansSluga  and  John  Searle)."],
	"employment" : ["Acting  Assistant  Professor  of  Philosophy,  University  of  California,  San  Diego,  1973-75.", "Assistant  Professor,  University  of  California,  San  Diego,  1975-80.", "Associate  Professor,  University  of  California,  San  Diego,  1980-89.Visiting","Associate  Professor,  California  Institute  of  Technology,  Spring,  1984.","Graduate  Advisor  (director  of  graduate  studies),  University  of  California,  San  Diego,  1982-83,  1985-88,  1990-1992,  1999-2003.","Current  position:  Professor,  University  of  California,  San  Diego,  1989-2008.    Professor,  Above  Scale  (Distinguished  Professor),  University  of  California,  San  Diego,  2008-present.","Holder  of  the  Valtz  Family  Chair  in  Philosophy,  UCSD,  July-2011-present.","Concurrent  position:  Research  Professor  for  five  year-term,  Philosophy,  University  of  Arizona.    This  position  involves  no  teaching  duties  and  provides  forseveralweeks  per  year  in  residence  at  the  University  of  Arizona  Philosophy  Department.","Adjunct  Professor,  School  of  Law,  University  of  San  Diego,  August-December,  2008.","Visiting  Professor,  University  of  California,  Davis,  Winter-Spring,  1990.","Philosophy  Department  Chair,  University  of  California,  San  Diego,  1992-1996.","Visiting  Olmsted  Professor  in  Political  Science  and  the  Program  onEthics,  Politics,  and  Economics,  Yale  University,  Fall,  1996."]
}
